version: '3.8'

services:
  jenkins:
    build:
      # Dockerfile이 있는 디렉토리 경로
      context: .
    environment:
      node.name: jenkins
    ports:
      - "8000:8080"
      - "50010:50000"
    volumes:
      - ./scripts:/var/jenkins_home/scripts
      - jenkins-data:/var/jenkins_home
    # 컨테이너가 중단되면 자동으로 재시작하도록 설정
    restart: unless-stopped

volumes:
  jenkins-data:
